server:
  port : 8080
  connection-timeout: 20000
  servlet:
    display-name: Your project
    context-path: /your context

spring:
  data:
    mongodb:
      database: "name of db"

resources: '${user.dir}/src/main/resources'
certs: '${resources}/certs'
bot-config: '${resources}/bot-config.json'

logging:
  file: ${resources}/logs/your_log.log
  path: ${resources}/logs
  level:
    ROOT: DEBUG

crypto:
  password: 'AES256bits'

management:
  endpoint:
    health:
      show-details: always

cors:
  allowed-origin: "*"
  url-mapping: "/**"

