server:
  port: 8080
  connection-timeout: 20000
  servlet:
    display-name: BotApp
    context-path: "/botapp"

concurrency:
  pools:
    bot:
      core-size: 8
      max-size: 10
      queue-capacity: 1000
      thread-name-prefix: bot-thread-pool  
    sse:
      core-size: 10
      max-size: 100
      queue-capacity: 1000
      thread-name-prefix: sse-thread-pool

resources: src/main/resources
certs: certs
bot-config: ${resources}/bot-config.json

logging:
  file: ${resources}/logs/bot-app.log
  level:
    ROOT: INFO
    com.symphony.ms.bot.sdk.internal: DEBUG

management:
  endpoints:
    web:
      base-path: /monitor
  endpoint:
    health:
      show-details: always

cors:
  allowed-origin: "*"
  url-mapping: "/**"

xss:
  url-mapping: "/**"

request-origin:
  origin-header: "x-origin-token"
  url-mapping: "/notification"

restclient:
  timeout: 35000

