features:
  commandFeedback: enabled
  transactionIdOnError: enabled
  eventUnexpectedErrorMessage: "Something went wrong, please contact your Symphony administrator"
  notificationBaseUrl: "http://localhost:8080"
