server:
  port: 8080
  connection-timeout: 20000
  servlet:
    display-name: BotApp
    context-path: "/botapp"

concurrency:
  bot:
    pool:
      core-size: 8
      max-size: 10
      queue-capacity: 1000
      thread-name-prefix: bot-thread-pool
  sse:
    pool:
      core-size: 10
      max-size: 100
      queue-capacity: 0
      thread-name-prefix: sse-thread-pool
    subscriber:
      queue-capacity: 10
      queue-timeout: 5000

logging:
  file: logs/bot-app.log
  level:
    ROOT: INFO
    com.symphony.bdk.bot.sdk: DEBUG

management:
  endpoints:
    web:
      base-path: /monitor
      exposure:
        include: health, info, prometheus
  endpoint:
    health:
      show-details: always
  health:
    defaults:
      enabled: false
  symphony-api-client-version: '@symphony.apiclient.version@'

restclient:
  timeout: 35000

