features:
  commandFeedback: enabled
  transactionIdOnError: enabled
  eventUnexpectedErrorMessage: "Something went wrong, please contact your Symphony administrator"
  notificationBaseUrl: "http://localhost:8080"
  isPublicRoomAllowed: false
  publicRoomNotAllowedMessage: Sorry, I cannot be added to public rooms
  publicRoomNotAllowedTemplate: alert
  publicRoomNotAllowedTemplateMap:
    message:
      title: Bot not allowed in public rooms
      content: Sorry, I cannot be added to public rooms
  spreadsheetPresenceTimeInterval: 10000